### ISSUE TITLE
 frida-server some error ? 

### ISSUE THREAD

**Issue by ZhuJD-China** [1633455355/xianyu#1]
F:\Anaconda\python.exe D:\EmbeddingsSearch\xianyu\main.py 
2023-07-04 09:44:04,362 app.py-line:93 <AppMsgSender> [DEBUG] 旧token获取失败，重新获取token
2023-07-04 09:44:04,768 app.py-line:111 <AppMsgSender> [INFO] token请求成功
Traceback (most recent call last):
  File "D:\EmbeddingsSearch\xianyu\main.py", line 1, in <module>
    from core.service.service import router
  File "D:\EmbeddingsSearch\xianyu\core\service\service.py", line 10, in <module>
    from core.task.task_manage import XianYuTask
  File "D:\EmbeddingsSearch\xianyu\core\task\task_manage.py", line 5, in <module>
    from .xy_task import start_task
  File "D:\EmbeddingsSearch\xianyu\core\task\xy_task.py", line 12, in <module>
    api = Api()
  File "D:\EmbeddingsSearch\xianyu\core\api\api.py", line 29, in __init__
    self.xian_yu = XianYu(js_path)
  File "D:\EmbeddingsSearch\xianyu\core\frida\xianyu.py", line 27, in __init__
    self.process = frida.get_remote_device().attach(self.app_name)
  File "F:\Anaconda\lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "F:\Anaconda\lib\site-packages\frida\core.py", line 1010, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
  File "F:\Anaconda\lib\site-packages\frida\core.py", line 1134, in _pid_of
    return self.get_process(target).pid
  File "F:\Anaconda\lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "F:\Anaconda\lib\site-packages\frida\core.py", line 899, in get_process
    for process in self._impl.enumerate_processes()
frida.ServerNotRunningError: unable to connect to remote frida-server

Process finished with exit code 1

**Comment by 23233** [comment]
@ZhuJD-China  解决了吗?

**Comment by ZhuJD-China** [comment]
手机端frida-server起起来正常就ok
